version: '3.4'
services:
  product:
    build:
      context: ..
      dockerfile: ./ArqHexagonalModular/Dockerfile
    ports:
      - 8081:8081
    environment:
      JAVA_OPTS: -Xmx70m -Duser.timezone=Europe/Madrid
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  default:
    driver: bridge
